
formatters:
  default:
    format: '[%(levelname)s] [%(name)s] %(message)s'
  time:
    format: '[%(asctime)s] [%(levelname)-8s] [%(name)s] %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
handlers:
  tool_file:
    level: WARNING
    class: logging.FileHandler
    filename: placeholder  # must be set when the path is known!
    formatter: default
  workflow_file:
    level: WARNING
    class: logging.FileHandler
    filename: placeholder  # must be set when the path is known!
    formatter: default
  console:
    level: INFO
    class: logging.StreamHandler
    stream: ext://sys.stdout
    formatter: default
  galaxy_console:
    level: ERROR
    class: logging.StreamHandler
    stream: ext://sys.stdout
    formatter: default
loggers:
  root:
    handlers: [galaxy_console]
  tool:
    level: INFO
    handlers: [console, tool_file]
  workflow:
    level: INFO
    handlers: [console, workflow_file]
version: 1