
formatters:
  default:
    format: '[%(levelname)s] [%(name)s] %(message)s'
  time:
    format: '[%(asctime)s] [%(levelname)-8s] [%(name)s] %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
handlers:
  # gxtool2janis
  gxtool2janis_console:
    level: INFO
    class: logging.StreamHandler
    stream: ext://sys.stdout
    formatter: default
  gxtool2janis_file:
    level: INFO
    class: logging.FileHandler
    filename: gxtool2janis.log
    formatter: default
  # galaxy
  galaxy_console:
    level: ERROR
    class: logging.StreamHandler
    stream: ext://sys.stdout
    formatter: default
  galaxy_file:
    level: ERROR
    class: logging.FileHandler
    filename: galaxy.log
    formatter: default
loggers:
  gxtool2janis:
    level: INFO
    handlers: [gxtool2janis_console, gxtool2janis_file]
  root:
    handlers: [galaxy_console, galaxy_file]
version: 1